### ISSUE TITLE
Cordova Camera Plugin Issue

### ISSUE THREAD

**Issue by Vishwa17** [OfficeDev/Cordova-Mail-App-Code-Sample#1]
Hi Team,

Facing this issue: 
Please can you help, the plugin of CORDOVA CAMERA the callbackContext is returning NULL and the app get crash..
Can you help us why this is happening in Android 5.0.0 and 4.4.2  as well as.. Can u do something in codova camera plugin and some try catch where as null value come the app should not crash.
We have created our app in Sencha touch is 2.4.x , cordova 5.1.1 

D/AndroidRuntime(14743): Shutting down VM

E/AndroidRuntime(14743): FATAL EXCEPTION: main

E/AndroidRuntime(14743): Process: com.nielsen.nic, PID: 14743

E/AndroidRuntime(14743): java.lang.RuntimeException: Unable to resume activity {com.nielsen.nic/com.nielsen.nic.NIC}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=33, result=-1, data=null} to activity {com.nielsen.nic/com.nielsen.nic.NIC}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

E/AndroidRuntime(14743):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3346)

E/AndroidRuntime(14743):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3377)

E/AndroidRuntime(14743):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2728)

E/AndroidRuntime(14743):    at android.app.ActivityThread.access$900(ActivityThread.java:172)

E/AndroidRuntime(14743):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)

E/AndroidRuntime(14743):    at android.os.Handler.dispatchMessage(Handler.java:102)

E/AndroidRuntime(14743):    at android.os.Looper.loop(Looper.java:145)

E/AndroidRuntime(14743):    at android.app.ActivityThread.main(ActivityThread.java:5832)

E/AndroidRuntime(14743):    at java.lang.reflect.Method.invoke(Native Method)

E/AndroidRuntime(14743):    at java.lang.reflect.Method.invoke(Method.java:372)

E/AndroidRuntime(14743):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)

E/AndroidRuntime(14743):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

E/AndroidRuntime(14743): Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=33, result=-1, data=null} to activity {com.nielsen.nic/com.nielsen.nic.NIC}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

E/AndroidRuntime(14743):    at android.app.ActivityThread.deliverResults(ActivityThread.java:3974)

E/AndroidRuntime(14743):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3332)

E/AndroidRuntime(14743):    ... 11 more

E/AndroidRuntime(14743): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference

E/AndroidRuntime(14743):    at org.apache.cordova.camera.CameraLauncher.processResultFromCamera(CameraLauncher.java:404)

E/AndroidRuntime(14743):    at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:678)

E/AndroidRuntime(14743):    at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)

E/AndroidRuntime(14743):    at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:320)

E/AndroidRuntime(14743):    at android.app.Activity.dispatchActivityResult(Activity.java:6475)

E/AndroidRuntime(14743):    at android.app.ActivityThread.deliverResults(ActivityThread.java:3970)

E/AndroidRuntime(14743):    ... 12 more

W/ActivityManager( 4219):   Force finishing activity com.nielsen.nic/.NIC

D/FocusedStackFrame( 4219): Set to : 0

I/WindowManager( 4219): Screenshot max retries 4 of Token{25be1036 ActivityRecord{45b9dd1 u0 com.nielsen.nic/.NIC t312 f}} appWin=Window{9412bb1 u0 Starting com.nielsen.nic} drawState=4

E/ActivityManager( 4219): Invalid thumbnail dimensions: 576x576

**Comment by Vishwa17** [comment]
Can someone is there who can help me out

**Comment by Vishwa17** [comment]
Still the issue is exist.. Can some one help in this issue.
